"""empty message

Revision ID: 68806eac18a8
Revises: 
Create Date: 2020-04-23 13:58:01.409924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68806eac18a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actors')
    op.drop_table('movies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('jid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('jid', name='movies_pkey')
    )
    op.create_table('actors',
    sa.Column('jid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('jid', name='actors_pkey')
    )
    # ### end Alembic commands ###
